// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArchiveEntry } from "./ArchiveEntry";
import type { CoreCacheSnapshot } from "./CoreCacheSnapshot";

export type ArchiveResult = { action: string, entry: ArchiveEntry, cache: CoreCacheSnapshot, };
