// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ArchiveEntry = { original_relative_path: string, archive_relative_path: string, archived_at: string, content_hash: string, };
