// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportAcceptReport } from "./ImportAcceptReport";

export type BulkImportAcceptReport = { vault_path: string, accepted: Array<ImportAcceptReport>, errors: Array<string>, };
