// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityMetadata } from "./EntityMetadata";
import type { GraphHealthWarning } from "./GraphHealthWarning";
import type { GraphLink } from "./GraphLink";
import type { IndexSnapshot } from "./IndexSnapshot";

export type CoreCacheSnapshot = { schema_version: number, vault_path: string, entities_by_path: { [key in string]?: EntityMetadata }, graph_links: Array<GraphLink>, health_warnings: Array<GraphHealthWarning>, index: IndexSnapshot, updated_at: string, invalidation_reason: string | null, };
