// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DocumentIndexEntry = { current_path: string, metadata_path: string, layout_path: string, };
