// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreCacheSnapshot } from "./CoreCacheSnapshot";
import type { EntityUpgradeChange } from "./EntityUpgradeChange";

export type EntityUpgradeReport = { schema_version: number, vault_path: string, upgraded_at: string, manifest_path: string, backup_root: string, changes: Array<EntityUpgradeChange>, trashed_legacy_paths: Array<string>, cache: CoreCacheSnapshot, };
