// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityUpgradeChange } from "./EntityUpgradeChange";

export type EntityUpgradePreview = { schema_version: number, vault_path: string, changes: Array<EntityUpgradeChange>, legacy_paths: Array<string>, warnings: Array<string>, };
