// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EntityUpgradeChange = { source_path: string, target_path: string, entity_type: string, title: string, document_id: string, markdown_body: string, action: string, };
