// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GraphLink } from "./GraphLink";
import type { GraphRelationship } from "./GraphRelationship";

export type EntityMetadata = { document_id: string | null, current_path: string, title: string, entity_type: string, metadata_path: string | null, content_hash: string, backlinks: Array<GraphLink>, tags: Array<string>, relationships: Array<GraphRelationship>, unresolved_links: Array<GraphLink>, };
