// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExternalSourceFile = { source_relative_path: string, target_relative_path: string, file_kind: string, document_id: string | null, title: string | null, content_hash: string, copied: boolean, collision_renamed: boolean, skipped: boolean, reason: string | null, };
