// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalSourceFile } from "./ExternalSourceFile";

export type ExternalSourceScan = { source_path: string, source_kind: string, markdown_count: number, asset_count: number, ignored_count: number, files: Array<ExternalSourceFile>, warnings: Array<string>, };
