// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileLifecycleEntry } from "./FileLifecycleEntry";

export type FileLifecycleMutationReport = { action: string, message: string, changed_count: number, entries: Array<FileLifecycleEntry>, };
