// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileLifecycleEntry = { id: string, original_path: string, current_path: string, file_name: string, module_id: string | null, deleted_or_archived_at: string | null, size_bytes: bigint | null, can_restore: boolean, };
