// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalSourceFile } from "./ExternalSourceFile";
import type { ExternalSourceScan } from "./ExternalSourceScan";

export type FolderImportPreview = { source_path: string, vault_path: string, scan: ExternalSourceScan, target_root: string, planned_files: Array<ExternalSourceFile>, conflicts: Array<string>, warnings: Array<string>, };
