// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalSourceFile } from "./ExternalSourceFile";

export type FolderImportManifest = { schema_version: number, source_path: string, vault_path: string, target_root: string, imported_at: string, files: Array<ExternalSourceFile>, conflicts: Array<string>, warnings: Array<string>, };
