// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GraphLink = { source_path: string, target: string, link_type: string, raw: string, status: string, resolved_document_id: string | null, resolved_path: string | null, };
