// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GraphHealthWarning = { code: string, message: string, document_id: string | null, path: string | null, };
