// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StagedImportIndex } from "./StagedImportIndex";

export type IgnoredStagedImportReport = { vault_path: string, staged_file_path: string, ignored_at: string, index: StagedImportIndex, };
