// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImportAcceptanceOptions = { target_filename: string | null, tags: Array<string>, preserve_source_path: boolean, batch_tag: string | null, };
