// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreCacheSnapshot } from "./CoreCacheSnapshot";

export type ImportAcceptReport = { vault_path: string, staged_file_path: string, target_module: string, accepted_relative_path: string, accepted_manifest_path: string, accepted_at: string, warnings: Array<string>, cache: CoreCacheSnapshot, };
