// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentIndexEntry } from "./DocumentIndexEntry";
import type { RebuildPolicy } from "./RebuildPolicy";

export type IndexSnapshot = { schema_version: number, path_policy: string, documents_by_id: { [key in string]?: DocumentIndexEntry }, document_ids_by_path: { [key in string]?: string }, orphaned_document_ids: Array<string>, duplicate_identity_conflicts: Array<string>, updated_at: string, rebuild_policy: RebuildPolicy, };
