// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GraphHealthWarning } from "./GraphHealthWarning";
import type { GraphLink } from "./GraphLink";
import type { NavigatorModuleSummary } from "./NavigatorModuleSummary";

export type NavigatorSnapshot = { schema_version: number, vault_path: string, navigator_path: string, index_path: string, markdown: string, module_summaries: Array<NavigatorModuleSummary>, health_warnings: Array<GraphHealthWarning>, managed_block_warnings: Array<string>, backlinks: Array<GraphLink>, search_index_path: string, updated_at: string, };
