// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RebuildPolicy = { rebuild_from_documents_folder: boolean, rebuild_from_markdown_uuid_comments: boolean, treat_index_as_cache: boolean, };
