// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SearchIndexEntry = { path: string, document_id: string | null, title: string, entity_type: string, tags: Array<string>, headings: Array<string>, excerpt: string, searchable_text: string, };
