// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchIndexEntry } from "./SearchIndexEntry";

export type SearchIndexSnapshot = { schema_version: number, vault_path: string, index_path: string, entries: Array<SearchIndexEntry>, updated_at: string, source_cache_updated_at: string, };
