// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SnapshotVaultShape } from "./SnapshotVaultShape";

export type SnapshotRestorePreview = { snapshot_path: string, target_vault_path: string, file_count: number, snapshot_shape: SnapshotVaultShape, direct_restore_allowed: boolean, blocked_reason: string | null, legacy_file_count: number, active_v3_file_count: number, legacy_file_paths: Array<string>, active_v3_file_paths: Array<string>, hidden_runtime_file_paths: Array<string>, recommended_action: string, conflicts: Array<string>, warnings: Array<string>, };
