// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StagedImportIndex } from "./StagedImportIndex";
import type { StagedImportRecord } from "./StagedImportRecord";

export type SnapshotStageReport = { snapshot_path: string, target_vault_path: string, staged_root: string, staged_at: string, staged_files: Array<StagedImportRecord>, index: StagedImportIndex, warnings: Array<string>, };
