// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreCacheSnapshot } from "./CoreCacheSnapshot";
import type { SnapshotFileEntry } from "./SnapshotFileEntry";

export type SnapshotRestoreReport = { snapshot_path: string, target_vault_path: string, restored_at: string, restored_files: Array<SnapshotFileEntry>, conflicts: Array<string>, warnings: Array<string>, cache: CoreCacheSnapshot, };
