// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SnapshotFileEntry = { relative_path: string, file_kind: string, content_hash: string, byte_len: bigint, };
