// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SnapshotVaultShape = "v3_active_snapshot" | "legacy_bentolife_snapshot" | "mixed_or_unknown_snapshot";
