// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StagedImportRecord } from "./StagedImportRecord";

export type StagedImportIndex = { schema_version: number, vault_path: string, updated_at: string, records: Array<StagedImportRecord>, hidden_system_count: number, hidden_system_files: Array<string>, warnings: Array<string>, };
