// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StagedImportRecord = { staged_file_path: string, original_source_path: string | null, source_kind: string, detected_title: string | null, detected_tags: Array<string>, detected_links: Array<string>, detected_checklists: number, suggested_module: string, accepted: boolean, ignored: boolean, conflict_status: string | null, };
