// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThemeManifest = { schema_version: number, theme_id: string, scope: string, css_path: string | null, json_path: string | null, active: boolean, };
