// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TrashEntry = { original_relative_path: string, trash_relative_path: string, trashed_at: string, content_hash: string, };
