// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreCacheSnapshot } from "./CoreCacheSnapshot";
import type { TrashEntry } from "./TrashEntry";

export type TrashResult = { action: string, entry: TrashEntry, cache: CoreCacheSnapshot, };
