// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VaultSnapshotPreview = { source_vault_path: string, snapshot_path: string, file_count: number, total_bytes: bigint, warnings: Array<string>, };
