// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SnapshotFileEntry } from "./SnapshotFileEntry";

export type VaultSnapshotManifest = { schema_version: number, source_vault_path: string, snapshot_path: string, created_at: string, source_machine: string, files: Array<SnapshotFileEntry>, warnings: Array<string>, };
