// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceStateContract = { schema_version: number, workspace_name: string, index_path: string, default_theme: string, language: string, architect_active_tab: string, };
