// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceSchema = { schema_version: number, vault_folder: string, app_folder: string, index_path: string, };
